spring:
  redis:
    host: 192.168.1.154
    password: redis123456
    port: 6379
  datasource:

  application:
    name: sensitivewd-server
server:
  port: 8686
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: cn.modo.sensitive.pojo
env: dev
